"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[⟨$directory⟩](#67ffd6)
[𜰘𜰉𜰙 ](#ff5b5b bold)
'''

[directory]
style = "fg:#67ffd6 bold"
format = '[$path]($style)'

[package]
disabled = true
