"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[╔╡$username╞╡$directory](#f5edb5)
[╚ ](#f5edb5)
'''

[username]
show_always = true
style_user = "fg:#f5edb5 bold bg:#f5edb5"
style_root = "fg:#f5edb5 bold bg:#f5edb5"
format = '[$user]($style)'

[directory]
style = "fg:#f5edb5 bold"
format = '[$path]($style)'


[package]
disabled = true
