"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
[╭─🮤$username🮥─🮤 $directory🮥](#f5edb5)
[╰───𜰚 ](#f5edb5)
'''

[username]
show_always = true
style_user = "fg:#ff5b5b bold"
style_root = "fg:#ff5b5b bold"
format = '[ $user ]($style)'

[directory]
style = "fg:#ff5b5b bold"


[package]
disabled = true