"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
[╔𜲀](#ff5b5b)$username
[╠𜲀 ](#ff5b5b)$directory
[╚═𜲂](#ff5b5b)
'''

[username]
show_always = true
style_user = "fg:#16fc5b bold"
style_root = "fg:#16fc5b bold"
format = '[ $user ]($style)'

[directory]
style = "fg:#16fc5b bold"


[package]
disabled = true