"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[⟨$directory⟩](#ff5b5b)
[𜰘𜰉𜰉𜰙 ](#f5edb5 bold)
'''

[directory]
style = "fg:#ff5b5b bold"
format = '[$path]($style)'

[package]
disabled = true
