"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[╔╡$username╞╡$directory](#f5edb5)
[╚ ](#f5edb5)
'''

[username]
show_always = true
style_user = "fg:#17121a bold bg:#f5edb5"
style_root = "fg:#17121a bold"
format = '[ $user ]($style)'

[directory]
style = "fg:#f5edb5 bold"


[package]
disabled = true
