"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[⟨$directory⟩](#f5b5ed)
[𜰘𜰉𜰉𜰙 ](#f5b5ed bold)
'''

[directory]
style = "fg:#f5b5ed bold"
format = '[$path]($style)'

[package]
disabled = true
