"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[$directory](#67ffd6)
[󰄾󰔰 ](#67ffd6)
'''

[directory]
style = "fg:#67ffd6 bold"
format = '[$path]($style)'


[package]
disabled = true
