"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[⟨$directory⟩](#e9eee6)
[𜰘𜰉𜰉𜰙 ](#e9eee6 bold)
'''

[directory]
style = "fg:#e9eee6 bold"
format = '[$path]($style)'

[package]
disabled = true
