"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[⟨$directory⟩](#f5edb5)
[𜰘𜰉𜰉𜰙](#f5edb5 bold)
'''

[directory]
style = "fg:#f5edb5 bold"
format = '[$path]($style)'

[package]
disabled = true
