# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ";ny"
    replace: "ñ"
  - trigger: ";NY"
    replace: "Ñ"

  # old english latin alphabet

  - trigger: ";wyn"
    replace: "ƿ"
  - trigger: ";WYN"
    replace: "Ƿ"

  - trigger: ";thorn"
    replace: "þ"
  - trigger: ";THORN"
    replace: "Þ"

  - trigger: ";ash"
    replace: "æ"
  - trigger: ";ASH"
    replace: "Æ"

  - trigger: ";edh"
    replace: "ð"
  - trigger: ";EDH"
    replace: "Ð"

  # greek alphabet

  - trigger: ";alpha"
    replace: "α"

  - trigger: ";beta"
    replace: "β"

  - trigger: ";gamma1"
    replace: "ɣ"
  - trigger: ";gamma2"
    replace: "γ"
  - trigger: ";GAMMA"
    replace: "Γ"

  - trigger: ";delta"
    replace: "δ"
  - trigger: ";DELTA"
    replace: "Δ"

  - trigger: ";epsilon"
    replace: "ε"

  - trigger: ";zeta"
    replace: "ζ"

  - trigger: ";eta"
    replace: "η"

  - trigger: ";theta"
    replace: "θ"
  - trigger: ";THETA"
    replace: "Θ"

  - trigger: ";iota"
    replace: "ι"

  - trigger: ";kappa"
    replace: "κ"

  - trigger: ";lamda"
    replace: "λ"
  - trigger: ";LAMDA"
    replace: "Λ"

  - trigger: ";mu"
    replace: "μ"

  - trigger: ";nu"
    replace: "ν"

  - trigger: ";xi"
    replace: "ξ"
  - trigger: ";XI"
    replace: "Ξ"

  - trigger: ";pi"
    replace: "π"
  - trigger: ";PI"
    replace: "Π"

  - trigger: ";rho"
    replace: "ρ"

  - trigger: ";sigma1"
    replace: "σ"
  - trigger: ";sigma2"
    replace: "ς"
  - trigger: ";SIGMA"
    replace: "Σ"

  - trigger: ";tau"
    replace: "τ"

  - trigger: ";upsilon"
    replace: "υ"
  - trigger: ";UPSILON"
    replace: "Υ"

  - trigger: ";phi1"
    replace: "ɸ"
  - trigger: ";phi2"
    replace: "φ"
  - trigger: ";PHI"
    replace: "Φ"

  - trigger: ";chi"
    replace: "χ"

  - trigger: ";psi"
    replace: "ψ"
  - trigger: ";PSI"
    replace: "Ψ"

  - trigger: ";omega"
    replace: "ω"
  - trigger: ";OMEGA"
    replace: "Ω"

  # kanji

  - trigger: "`~zero"
    replace: "零"

  - trigger: "`~ichi"
    replace: "一"

  - trigger: "`~ni"
    replace: "二"

  - trigger: "`~yon"
    replace: "四"

  - trigger: "`~go"
    replace: "五"

  - trigger: "`~roku"
    replace: "六"

  - trigger: "`~nana"
    replace: "七"

  - trigger: "`~hachi"
    replace: "八"

  - trigger: "`~kyu"
    replace: "九"

  - trigger: "`~juu"
    replace: "十"

  - trigger: "`~hyaku"
    replace: "百"

  - trigger: "`~sen"
    replace: "千"

  - trigger: "`~kitana"
    replace: "汚"

  - trigger: "`~ou"
    replace: "王"

  - trigger: "`~tabe"
    replace: "食"

  - trigger: "`~ma"
    replace: "魔"

  # hiragana

  - trigger: "`a"
    replace: "あ"
  - trigger: "`i"
    replace: "い"
  - trigger: "`u"
    replace: "う"
  - trigger: "`e"
    replace: "え"
  - trigger: "`o"
    replace: "お"

  - trigger: "`Sa"
    replace: "ぁ"
  - trigger: "`Si"
    replace: "ぃ"
  - trigger: "`Su"
    replace: "ぅ"
  - trigger: "`Se"
    replace: "ぇ"
  - trigger: "`So"
    replace: "ぉ"

  - trigger: "`V2"
    replace: "ー"
  - trigger: "`C2"
    replace: "っ"

  - trigger: "`ka"
    replace: "か"
  - trigger: "`ki"
    replace: "き"
  - trigger: "`ku"
    replace: "く"
  - trigger: "`ke"
    replace: "け"
  - trigger: "`ko"
    replace: "こ"
  - trigger: "`ga"
    replace: "が"
  - trigger: "`gi"
    replace: "ぎ"
  - trigger: "`gu"
    replace: "ぐ"
  - trigger: "`ge"
    replace: "げ"
  - trigger: "`go"
    replace: "ご"

  - trigger: "`kya"
    replace: "きゃ"
  - trigger: "`kyu"
    replace: "きゅ"
  - trigger: "`kyo"
    replace: "きょ"
  - trigger: "`gya"
    replace: "ぎゃ"
  - trigger: "`gyu"
    replace: "ぎゅ"
  - trigger: "`gyo"
    replace: "ぎょ"

  - trigger: "`sa"
    replace: "さ"
  - trigger: "`shi"
    replace: "し"
  - trigger: "`su"
    replace: "す"
  - trigger: "`se"
    replace: "せ"
  - trigger: "`so"
    replace: "そ"
  - trigger: "`za"
    replace: "ざ"
  - trigger: "`zhi"
    replace: "じ"
  - trigger: "`zu"
    replace: "ず"
  - trigger: "`ze"
    replace: "ぜ"
  - trigger: "`zo"
    replace: "ぞ"

  - trigger: "`sha"
    replace: "しゃ"
  - trigger: "`shu"
    replace: "しゅ"
  - trigger: "`sho"
    replace: "しょ"
  - trigger: "`zha"
    replace: "じゃ"
  - trigger: "`zhu"
    replace: "じゅ"
  - trigger: "`zho"
    replace: "じょ"

  - trigger: "`ta"
    replace: "た"
  - trigger: "`chi"
    replace: "ち"
  - trigger: "`tsu"
    replace: "つ"
  - trigger: "`te"
    replace: "て"
  - trigger: "`to"
    replace: "と"
  - trigger: "`da"
    replace: "だ"
  - trigger: "`ji"
    replace: "ぢ"
  - trigger: "`dzu"
    replace: "づ"
  - trigger: "`de"
    replace: "で"
  - trigger: "`do"
    replace: "ど"

  - trigger: "`cha"
    replace: "ちゃ"
  - trigger: "`chu"
    replace: "ちゅ"
  - trigger: "`cho"
    replace: "ちょ"
  - trigger: "`ja"
    replace: "ぢゃ"
  - trigger: "`ju"
    replace: "ぢゅ"
  - trigger: "`jo"
    replace: "ぢょ"

  - trigger: "`na"
    replace: "な"
  - trigger: "`ni"
    replace: "に"
  - trigger: "`nu"
    replace: "ぬ"
  - trigger: "`ne"
    replace: "ね"
  - trigger: "`no"
    replace: "の"

  - trigger: "`nya"
    replace: "にゃ"
  - trigger: "`nyu"
    replace: "にゅ"
  - trigger: "`nyo"
    replace: "にょ"

  - trigger: "`ha"
    replace: "は"
  - trigger: "`hi"
    replace: "ひ"
  - trigger: "`fu"
    replace: "ふ"
  - trigger: "`he"
    replace: "へ"
  - trigger: "`ho"
    replace: "ほ"
  - trigger: "`ba"
    replace: "ば"
  - trigger: "`bi"
    replace: "び"
  - trigger: "`bu"
    replace: "ぶ"
  - trigger: "`be"
    replace: "べ"
  - trigger: "`bo"
    replace: "ぼ"
  - trigger: "`pa"
    replace: "ぱ"
  - trigger: "`pi"
    replace: "ぴ"
  - trigger: "`pu"
    replace: "ぷ"
  - trigger: "`pe"
    replace: "ぺ"
  - trigger: "`po"
    replace: "ぽ"

  - trigger: "`hya"
    replace: "ひゃ"
  - trigger: "`hyu"
    replace: "ひゅ"
  - trigger: "`hyo"
    replace: "ひょ"
  - trigger: "`bya"
    replace: "びゃ"
  - trigger: "`byu"
    replace: "びゅ"
  - trigger: "`byo"
    replace: "びょ"
  - trigger: "`pya"
    replace: "ぴゃ"
  - trigger: "`pyu"
    replace: "ぴゅ"
  - trigger: "`pyo"
    replace: "ぴょ"

  - trigger: "`ma"
    replace: "ま"
  - trigger: "`mi"
    replace: "み"
  - trigger: "`mu"
    replace: "む"
  - trigger: "`me"
    replace: "め"
  - trigger: "`mo"
    replace: "も"

  - trigger: "`mya"
    replace: "みゃ"
  - trigger: "`myu"
    replace: "みゅ"
  - trigger: "`myo"
    replace: "みょ"

  - trigger: "`ya"
    replace: "や"
  - trigger: "`yu"
    replace: "ゆ"
  - trigger: "`yo"
    replace: "よ"

  - trigger: "`Sya"
    replace: "ゃ"
  - trigger: "`Syu"
    replace: "ゅ"
  - trigger: "`Syo"
    replace: "ょ"

  - trigger: "`ra"
    replace: "ら"
  - trigger: "`ri"
    replace: "り"
  - trigger: "`ru"
    replace: "る"
  - trigger: "`re"
    replace: "れ"
  - trigger: "`ro"
    replace: "ろ"

  - trigger: "`rya"
    replace: "りゃ"
  - trigger: "`ryu"
    replace: "りゅ"
  - trigger: "`ryo"
    replace: "りょ"

  - trigger: "`wa"
    replace: "わ"
  - trigger: "`wo"
    replace: "を"

  - trigger: "`N"
    replace: "ん"

  # hiragana

  - trigger: "`!a"
    replace: "ア"
  - trigger: "`!i"
    replace: "イ"
  - trigger: "`!u"
    replace: "ウ"
  - trigger: "`!e"
    replace: "エ"
  - trigger: "`!o"
    replace: "オ"

  - trigger: "`!Sa"
    replace: "ァ"
  - trigger: "`!Si"
    replace: "ィ"
  - trigger: "`!Su"
    replace: "ゥ"
  - trigger: "`!Se"
    replace: "ェ"
  - trigger: "`!So"
    replace: "ォ"

  - trigger: "`!C2"
    replace: "ッ"

  - trigger: "`!ka"
    replace: "カ"
  - trigger: "`!ki"
    replace: "キ"
  - trigger: "`!ku"
    replace: "ク"
  - trigger: "`!ke"
    replace: "ケ"
  - trigger: "`!ko"
    replace: "コ"
  - trigger: "`!ga"
    replace: "ガ"
  - trigger: "`!gi"
    replace: "ギ"
  - trigger: "`!gu"
    replace: "グ"
  - trigger: "`!ge"
    replace: "ゲ"
  - trigger: "`!go"
    replace: "ゴ"

  - trigger: "`!kya"
    replace: "キャ"
  - trigger: "`!kyu"
    replace: "キュ"
  - trigger: "`!kyo"
    replace: "キョ"
  - trigger: "`!gya"
    replace: "ギャ"
  - trigger: "`!gyu"
    replace: "ギュ"
  - trigger: "`!gyo"
    replace: "ギョ"

  - trigger: "`!sa"
    replace: "サ"
  - trigger: "`!shi"
    replace: "シ"
  - trigger: "`!su"
    replace: "ス"
  - trigger: "`!se"
    replace: "セ"
  - trigger: "`!so"
    replace: "ソ"
  - trigger: "`!za"
    replace: "ザ"
  - trigger: "`!zhi"
    replace: "ジ"
  - trigger: "`!zu"
    replace: "ズ"
  - trigger: "`!ze"
    replace: "ゼ"
  - trigger: "`!zo"
    replace: "ゾ"

  - trigger: "`!sha"
    replace: "シャ"
  - trigger: "`!shu"
    replace: "シュ"
  - trigger: "`!sho"
    replace: "ショ"
  - trigger: "`!zha"
    replace: "ジャ"
  - trigger: "`!zhu"
    replace: "ジュ"
  - trigger: "`!zho"
    replace: "ジョ"

  - trigger: "`!ta"
    replace: "タ"
  - trigger: "`!chi"
    replace: "チ"
  - trigger: "`!tsu"
    replace: "ツ"
  - trigger: "`!te"
    replace: "テ"
  - trigger: "`!to"
    replace: "ト"
  - trigger: "`!da"
    replace: "ダ"
  - trigger: "`!ji"
    replace: "ヂ"
  - trigger: "`!dzu"
    replace: "ヅ"
  - trigger: "`!de"
    replace: "デ"
  - trigger: "`!do"
    replace: "ド"

  - trigger: "`!cha"
    replace: "チャ"
  - trigger: "`!chu"
    replace: "チュ"
  - trigger: "`!cho"
    replace: "チョ"
  - trigger: "`!ja"
    replace: "ヂャ"
  - trigger: "`!ju"
    replace: "ヂュ"
  - trigger: "`!jo"
    replace: "ヂョ"

  - trigger: "`!na"
    replace: "ナ"
  - trigger: "`!ni"
    replace: "ニ"
  - trigger: "`!nu"
    replace: "ヌ"
  - trigger: "`!ne"
    replace: "ネ"
  - trigger: "`!no"
    replace: "ノ"

  - trigger: "`!nya"
    replace: "ニャ"
  - trigger: "`!nyu"
    replace: "ニュ"
  - trigger: "`!nyo"
    replace: "ニョ"

  - trigger: "`!ha"
    replace: "ハ"
  - trigger: "`!hi"
    replace: "ヒ"
  - trigger: "`!fu"
    replace: "フ"
  - trigger: "`!he"
    replace: "ヘ"
  - trigger: "`!ho"
    replace: "ホ"
  - trigger: "`!ba"
    replace: "バ"
  - trigger: "`!bi"
    replace: "ビ"
  - trigger: "`!bu"
    replace: "ブ"
  - trigger: "`!be"
    replace: "ベ"
  - trigger: "`!bo"
    replace: "ボ"
  - trigger: "`!pa"
    replace: "パ"
  - trigger: "`!pi"
    replace: "ピ"
  - trigger: "`!pu"
    replace: "プ"
  - trigger: "`!pe"
    replace: "ペ"
  - trigger: "`!po"
    replace: "ポ"

  - trigger: "`!hya"
    replace: "ヒャ"
  - trigger: "`!hyu"
    replace: "ヒュ"
  - trigger: "`!hyo"
    replace: "ヒョ"
  - trigger: "`!bya"
    replace: "ビャ"
  - trigger: "`!byu"
    replace: "ビュ"
  - trigger: "`!byo"
    replace: "ビョ"
  - trigger: "`!pya"
    replace: "ピャ"
  - trigger: "`!pyu"
    replace: "ピュ"
  - trigger: "`!pyo"
    replace: "ピョ"

  - trigger: "`!ma"
    replace: "マ"
  - trigger: "`!mi"
    replace: "ミ"
  - trigger: "`!mu"
    replace: "ム"
  - trigger: "`!me"
    replace: "メ"
  - trigger: "`!mo"
    replace: "モ"

  - trigger: "`!mya"
    replace: "ミャ"
  - trigger: "`!myu"
    replace: "ミュ"
  - trigger: "`!myo"
    replace: "ミョ"

  - trigger: "`!ya"
    replace: "ヤ"
  - trigger: "`!yu"
    replace: "ユ"
  - trigger: "`!yo"
    replace: "ヨ"

  - trigger: "`!Sya"
    replace: "ャ"
  - trigger: "`!Syu"
    replace: "ュ"
  - trigger: "`!Syo"
    replace: "ョ"

  - trigger: "`!ra"
    replace: "ラ"
  - trigger: "`!ri"
    replace: "リ"
  - trigger: "`!ru"
    replace: "ル"
  - trigger: "`!re"
    replace: "レ"
  - trigger: "`!ro"
    replace: "ロ"

  - trigger: "`!rya"
    replace: "リャ"
  - trigger: "`!ryu"
    replace: "リュ"
  - trigger: "`!ryo"
    replace: "リョ"

  - trigger: "`!wa"
    replace: "ワ"
  - trigger: "`!wo"
    replace: "ヲ"

  - trigger: "`!N"
    replace: "ン"

  # international phonetic alphabet

  - trigger: ";btrill"
    replace: "ʙ"
  - trigger: ";mn"
    replace: "ɱ"
  - trigger: ";vtap"
    replace: "ⱱ"
  - trigger: ";vw"
    replace: "ʋ"
  - trigger: ";rtap"
    replace: "ɾ"
  - trigger: ";sh"
    replace: "ʃ"
  - trigger: ";zh"
    replace: "ʒ"
  - trigger: ";sl"
    replace: "ɬ"
  - trigger: ";zl"
    replace: "ɮ"
  - trigger: ";rw"
    replace: "ɹ"
  - trigger: ";t'"
    replace: "ʈ"
  - trigger: ";d'"
    replace: "ɖ"
  - trigger: ";r'"
    replace: "ɽ"
  - trigger: ";s'"
    replace: "ʂ"
  - trigger: ";z'"
    replace: "ʐ"
  - trigger: ";rw'"
    replace: "ɻ"
  - trigger: ";l'"
    replace: "ɭ"
  - trigger: ";gy"
    replace: "ɟ"
  - trigger: ";nj"
    replace: "ɲ"
  - trigger: ";sj"
    replace: "ç"
  - trigger: ";zj"
    replace: "ʝ"
  - trigger: ";lj"
    replace: "ʎ"
  - trigger: ";ng"
    replace: "ŋ"
  - trigger: ";uu"
    replace: "ɰ"
  - trigger: ";wl"
    replace: "ʟ"
  - trigger: ";wg"
    replace: "ɢ"
  - trigger: ";wn"
    replace: "ɴ"
  - trigger: ";wr"
    replace: "ʀ"
  - trigger: ";chir"
    replace: "ʁ"
  - trigger: ";hs"
    replace: "ħ"
  - trigger: ";hz"
    replace: "ʕ"
  - trigger: ";."
    replace: "ʔ"
  - trigger: ";haah"
    replace: "ɦ"

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%b %d, %Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
