# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ";ny"
    replace: "ñ"

  - trigger: ";NY"
    replace: "Ñ"

  - trigger: ";btrill"
    replace: "ʙ"

  - trigger: ";phi1"
    replace: "ɸ"

  - trigger: ";phi2"
    replace: "φ"

  - trigger: ";PHI"
    replace: "Φ"

  - trigger: ";beta"
    replace: "β"

  - trigger: ";mn"
    replace: "ɱ"

  - trigger: ";vtap"
    replace: "ⱱ"

  - trigger: ";vw"
    replace: "ʋ"

  - trigger: ";theta"
    replace: "θ"

  - trigger: ";thorn"
    replace: "þ"

  - trigger: ";edh"
    replace: "ð"

  - trigger: ";rtap"
    replace: "ɾ"

  - trigger: ";sh"
    replace: "ʃ"

  - trigger: ";zh"
    replace: "ʒ"

  - trigger: ";sl"
    replace: "ɬ"

  - trigger: ";zl"
    replace: "ɮ"

  - trigger: ";rw"
    replace: "ɹ"

  - trigger: ";t'"
    replace: "ʈ"

  - trigger: ";d'"
    replace: "ɖ"

  - trigger: ";r'"
    replace: "ɽ"

  - trigger: ";s'"
    replace: "ʂ"

  - trigger: ";z'"
    replace: "ʐ"

  - trigger: ";rw'"
    replace: "ɻ"

  - trigger: ";l'"
    replace: "ɭ"

  - trigger: ";gy"
    replace: "ɟ"

  - trigger: ";nj"
    replace: "ɲ"

  - trigger: ";sj"
    replace: "ç"

  - trigger: ";zj"
    replace: "ʝ"

  - trigger: ";lj"
    replace: "ʎ"

  - trigger: ";ng"
    replace: "ŋ"

  - trigger: ";gamma1"
    replace: "ɣ"

  - trigger: ";gamma2"
    replace: "γ"

  - trigger: ";GAMMA"
    replace: "Γ"

  - trigger: ";uu"
    replace: "ɰ"

  - trigger: ";wl"
    replace: "ʟ"

  - trigger: ";wg"
    replace: "ɢ"

  - trigger: ";wn"
    replace: "ɴ"

  - trigger: ";wr"
    replace: "ʀ"

  - trigger: ";chix"
    replace: "χ"

  - trigger: ";chir"
    replace: "ʁ"

  - trigger: ";hs"
    replace: "ħ"

  - trigger: ";hz"
    replace: "ʕ"

  - trigger: ";."
    replace: "ʔ"

  - trigger: ";haah"
    replace: "ɦ"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
