[window]
opacity = 1

[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
size = 12

[colors]
cursor = { text = "#17121a", cursor = "#e9eee6" }
selection = { text = "#17121a", cursor = "#e9eee6" }
[colors.primary]
foreground = "#e9eee6"
background = "#17121a"
