[window]
opacity = 0.75

[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
size = 11

[colors]
cursor = { text = "#17121a", cursor = "#ff5b5b" }
selection = { text = "#17121a", cursor = "#ff5b5b" }
[colors.primary]
foreground = "#f5edb5"
background = "#17121a"
